apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-pvc
  namespace: default
spec:
  storageClassName: aws-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi